version: 0.2

phases:
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  baseDirectory: ./build
  files:
    - "**/*"
cache:
  paths:
    - node_modules/**/*