version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - aws s3 rm --recursive "s3://${websiteBucket}/"
      - npm run build
artifacts:
  base-directory: build
  files:
    - "**/*"
cache:
  paths:
    - ./node_modules/**/*